version: '3.8'
services:
  nodeserver:
    build:
      context: ./
    expose:
      - 8000
    depends_on:
      - database
    command: sh -c "yarn typeorm migration:run --config .docker.env && yarn docker"

  database:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - haufe_challangepgdata:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '8000:80'
    depends_on:
      - nodeserver
volumes:
  haufe_challangepgdata:
